AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MyGinbootProject

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  MyGinbootProjectAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  MyGinbootProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MyGinbootProjectAPI
      Environment:
        Variables:
          MY_VARIABLE: TEST
    Metadata:
      BuildMethod: makefile

Outputs:
  MyGinbootProjectEndpoint:
    Description: API Gateway MyGinbootProject Endpoint
    Value:
      Fn::Sub: https://${MyGinbootProjectAPI}.execute-api.${AWS::Region}.amazonaws.com/prod